FROM python:3.10-slim


ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /code

RUN pip install --upgrade pip
COPY ./req.txt .
RUN pip install -r req.txt

COPY . .
RUN chmod +x ./celery.sh

CMD ["gunicorn", "--reload", "--bind", "0.0.0.0:8000", "--worker-class", "uvicorn.workers.UvicornWorker", "--log-level", "INFO", "src.main:app"]